use crate::differ::{DatabaseDiff, DiffReport, DiffStatus, ObjectDiff, TableDiff};
use crate::schema::{ColumnDef, IndexDef, IndexColumn, ForeignKeyDef};

/// Generate a SQL sync file from a diff report.
///
/// Returns `(sql_content, warnings)`.
/// Warnings should be printed to stderr by the caller.
pub fn generate(report: &DiffReport) -> (String, Vec<String>) {
    let mut out = String::new();
    let mut warnings: Vec<String> = Vec::new();

    out.push_str("-- Generated by mysql-schema-diff\n");
    out.push_str(&format!("-- Base:  {}\n", report.base_label));
    out.push_str(&format!("-- Check: {}\n", report.check_label));
    out.push_str(&format!("-- Date:  {}\n", report.generated_at));
    out.push_str("--\n");
    out.push_str("-- Apply this file to the CHECK instance to sync it with BASE.\n");
    out.push_str("-- Lines with -- [WARN] are commented out: object exists in check but not base.\n");
    out.push_str("-- DELIMITER directives are for mysql CLI; strip them for programmatic APIs.\n");
    out.push('\n');
    out.push_str("SET FOREIGN_KEY_CHECKS = 0;\n");

    for db in &report.databases {
        if db.status == DiffStatus::Same {
            continue;
        }
        let (db_sql, db_warns) = generate_database(db);
        out.push_str(&db_sql);
        warnings.extend(db_warns);
    }

    out.push_str("\nSET FOREIGN_KEY_CHECKS = 1;\n");

    (out, warnings)
}

fn format_col_def(col: &ColumnDef) -> String {
    let mut parts = vec![col.column_type.clone()];
    if col.is_nullable { parts.push("NULL".into()); } else { parts.push("NOT NULL".into()); }
    if let Some(ref d) = col.column_default { parts.push(format!("DEFAULT {}", d)); }
    if !col.extra.is_empty() { parts.push(col.extra.clone()); }
    parts.join(" ")
}

fn generate_col_diffs(table_name: &str, col_diffs: &[ObjectDiff<ColumnDef>]) -> (String, Vec<String>) {
    let mut out = String::new();
    let mut warnings: Vec<String> = Vec::new();

    // Build ordinal map for AFTER clause
    let mut base_cols_by_ord: Vec<(u32, &str)> = col_diffs
        .iter()
        .filter_map(|d| d.base.as_ref().map(|c| (c.ordinal_position, c.name.as_str())))
        .collect();
    base_cols_by_ord.sort_by_key(|(ord, _)| *ord);

    for diff in col_diffs {
        match diff.status {
            DiffStatus::Same => {}
            DiffStatus::OnlyInBase => {
                let col = diff.base.as_ref().unwrap();
                let after = base_cols_by_ord
                    .iter()
                    .filter(|(ord, _)| *ord < col.ordinal_position)
                    .max_by_key(|(ord, _)| *ord)
                    .map(|(_, name)| format!(" AFTER `{}`", name))
                    .unwrap_or_default();
                out.push_str(&format!("ALTER TABLE `{}` ADD COLUMN `{}` {}{};\n", table_name, col.name, format_col_def(col), after));
            }
            DiffStatus::OnlyInCheck => {
                let col = diff.check.as_ref().unwrap();
                let msg = format!("column `{}` on `{}` exists in check but not in base", col.name, table_name);
                warnings.push(format!("[WARN] {} — review commented DROP in sync SQL", msg));
                out.push_str(&format!("-- [WARN] {}\n", msg));
                out.push_str(&format!("-- ALTER TABLE `{}` DROP COLUMN `{}`;\n", table_name, col.name));
            }
            DiffStatus::Changed => {
                let col = diff.base.as_ref().unwrap();
                out.push_str(&format!("ALTER TABLE `{}` MODIFY COLUMN `{}` {};\n", table_name, col.name, format_col_def(col)));
            }
        }
    }
    (out, warnings)
}

fn format_index_cols(cols: &[IndexColumn]) -> String {
    let mut sorted = cols.to_vec();
    sorted.sort_by_key(|c| c.seq_in_index);
    sorted.iter().map(|c| {
        if let Some(sp) = c.sub_part {
            format!("`{}`({})", c.column_name, sp)
        } else {
            format!("`{}`", c.column_name)
        }
    }).collect::<Vec<_>>().join(", ")
}

fn format_add_index(table_name: &str, idx: &IndexDef) -> String {
    let cols = format_index_cols(&idx.columns);
    let using = if idx.index_type == "HASH" { " USING HASH" } else { "" };
    if idx.name == "PRIMARY" {
        format!("ALTER TABLE `{}` ADD PRIMARY KEY ({}){};\n", table_name, cols, using)
    } else if idx.is_unique {
        format!("ALTER TABLE `{}` ADD UNIQUE INDEX `{}` ({}){};\n", table_name, idx.name, cols, using)
    } else {
        format!("ALTER TABLE `{}` ADD INDEX `{}` ({}){};\n", table_name, idx.name, cols, using)
    }
}

fn generate_idx_diffs(table_name: &str, idx_diffs: &[ObjectDiff<IndexDef>]) -> (String, Vec<String>) {
    let mut out = String::new();
    let mut warnings: Vec<String> = Vec::new();

    for diff in idx_diffs {
        match diff.status {
            DiffStatus::Same => {}
            DiffStatus::OnlyInBase => {
                out.push_str(&format_add_index(table_name, diff.base.as_ref().unwrap()));
            }
            DiffStatus::OnlyInCheck => {
                let idx = diff.check.as_ref().unwrap();
                let msg = format!("index `{}` on `{}` exists in check but not in base", idx.name, table_name);
                warnings.push(format!("[WARN] {} — review commented DROP in sync SQL", msg));
                out.push_str(&format!("-- [WARN] {}\n", msg));
                if idx.name == "PRIMARY" {
                    out.push_str(&format!("-- ALTER TABLE `{}` DROP PRIMARY KEY;\n", table_name));
                } else {
                    out.push_str(&format!("-- ALTER TABLE `{}` DROP INDEX `{}`;\n", table_name, idx.name));
                }
            }
            DiffStatus::Changed => {
                let base_idx = diff.base.as_ref().unwrap();
                // For Changed indexes: drop the old (by check name) then add base version
                // Using base name since both sides share the same name for Changed
                if base_idx.name == "PRIMARY" {
                    out.push_str(&format!("ALTER TABLE `{}` DROP PRIMARY KEY;\n", table_name));
                } else {
                    out.push_str(&format!("ALTER TABLE `{}` DROP INDEX `{}`;\n", table_name, base_idx.name));
                }
                out.push_str(&format_add_index(table_name, base_idx));
            }
        }
    }
    (out, warnings)
}

fn generate_fk_diffs(table_name: &str, fk_diffs: &[ObjectDiff<ForeignKeyDef>]) -> (String, Vec<String>) {
    let mut out = String::new();
    let mut warnings: Vec<String> = Vec::new();

    for diff in fk_diffs {
        match diff.status {
            DiffStatus::Same => {}
            DiffStatus::OnlyInBase => {
                let fk = diff.base.as_ref().unwrap();
                let cols = fk.columns.iter().map(|c| format!("`{}`", c)).collect::<Vec<_>>().join(", ");
                let ref_cols = fk.ref_columns.iter().map(|c| format!("`{}`", c)).collect::<Vec<_>>().join(", ");
                out.push_str(&format!(
                    "ALTER TABLE `{}` ADD CONSTRAINT `{}` FOREIGN KEY ({}) REFERENCES `{}` ({}) ON DELETE {} ON UPDATE {};\n",
                    table_name, fk.name, cols, fk.ref_table, ref_cols, fk.on_delete, fk.on_update
                ));
            }
            DiffStatus::OnlyInCheck => {
                let fk = diff.check.as_ref().unwrap();
                let msg = format!("foreign key `{}` on `{}` exists in check but not in base", fk.name, table_name);
                warnings.push(format!("[WARN] {} — review commented DROP in sync SQL", msg));
                out.push_str(&format!("-- [WARN] {}\n", msg));
                out.push_str(&format!("-- ALTER TABLE `{}` DROP FOREIGN KEY `{}`;\n", table_name, fk.name));
            }
            DiffStatus::Changed => {
                let base_fk = diff.base.as_ref().unwrap();
                let check_fk = diff.check.as_ref().unwrap();
                // Drop old FK (by check name) then add base version
                out.push_str(&format!("ALTER TABLE `{}` DROP FOREIGN KEY `{}`;\n", table_name, check_fk.name));
                let cols = base_fk.columns.iter().map(|c| format!("`{}`", c)).collect::<Vec<_>>().join(", ");
                let ref_cols = base_fk.ref_columns.iter().map(|c| format!("`{}`", c)).collect::<Vec<_>>().join(", ");
                out.push_str(&format!(
                    "ALTER TABLE `{}` ADD CONSTRAINT `{}` FOREIGN KEY ({}) REFERENCES `{}` ({}) ON DELETE {} ON UPDATE {};\n",
                    table_name, base_fk.name, cols, base_fk.ref_table, ref_cols, base_fk.on_delete, base_fk.on_update
                ));
            }
        }
    }
    (out, warnings)
}

fn generate_table_diffs(tables: &[TableDiff], db_name: &str) -> (String, Vec<String>) {
    let mut out = String::new();
    let mut warnings: Vec<String> = Vec::new();

    for table in tables {
        match table.status {
            DiffStatus::Same => {}
            DiffStatus::OnlyInCheck => {
                let msg = format!("table `{}` in `{}` exists in check but not in base", table.name, db_name);
                warnings.push(format!("[WARN] {} — review commented DROP in sync SQL", msg));
                out.push_str(&format!("-- [WARN] {}\n-- DROP TABLE IF EXISTS `{}`;\n\n", msg, table.name));
            }
            DiffStatus::OnlyInBase => {
                // Full CREATE TABLE implemented in Task 7; stub for now
                out.push_str(&format!("-- TODO: CREATE TABLE `{}` (implemented in Task 7)\n\n", table.name));
            }
            DiffStatus::Changed => {
                let (col_sql, col_warns) = generate_col_diffs(&table.name, &table.column_diffs);
                out.push_str(&col_sql);
                warnings.extend(col_warns);
                let (idx_sql, idx_warns) = generate_idx_diffs(&table.name, &table.index_diffs);
                out.push_str(&idx_sql);
                warnings.extend(idx_warns);
                let (fk_sql, fk_warns) = generate_fk_diffs(&table.name, &table.fk_diffs);
                out.push_str(&fk_sql);
                warnings.extend(fk_warns);
            }
        }
    }
    (out, warnings)
}

fn generate_database(db: &DatabaseDiff) -> (String, Vec<String>) {
    let mut out = String::new();
    let mut warnings: Vec<String> = Vec::new();

    out.push_str(&format!(
        "\n-- ============================================================\n\
         -- Database: {}\n\
         -- ============================================================\n",
        db.name
    ));

    match db.status {
        DiffStatus::OnlyInCheck => {
            let msg = format!("database `{}` exists in check but not in base", db.name);
            warnings.push(format!("[WARN] {} — review commented DROP in sync SQL", msg));
            out.push_str(&format!("-- [WARN] {}\n", msg));
            out.push_str(&format!("-- DROP DATABASE IF EXISTS `{}`;\n", db.name));
        }
        DiffStatus::OnlyInBase => {
            out.push_str(&format!("CREATE DATABASE IF NOT EXISTS `{}`;\n", db.name));
            out.push_str(&format!("USE `{}`;\n\n", db.name));
            let (t_sql, t_warns) = generate_table_diffs(&db.tables, &db.name);
            out.push_str(&t_sql);
            warnings.extend(t_warns);
        }
        DiffStatus::Changed => {
            out.push_str(&format!("USE `{}`;\n\n", db.name));
            let (t_sql, t_warns) = generate_table_diffs(&db.tables, &db.name);
            out.push_str(&t_sql);
            warnings.extend(t_warns);
        }
        DiffStatus::Same => {}
    }

    (out, warnings)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::differ::*;

    fn empty_report() -> DiffReport {
        DiffReport {
            base_label: "base".into(),
            check_label: "check".into(),
            generated_at: "2026-01-01".into(),
            databases: vec![],
        }
    }

    fn db_diff(name: &str, status: DiffStatus) -> DatabaseDiff {
        DatabaseDiff {
            name: name.into(),
            status,
            tables: vec![],
            views: vec![],
            procedures: vec![],
            functions: vec![],
            triggers: vec![],
        }
    }

    fn col(name: &str, col_type: &str, nullable: bool, default: Option<&str>, extra: &str, pos: u32) -> ColumnDef {
        ColumnDef {
            name: name.into(),
            column_type: col_type.into(),
            is_nullable: nullable,
            column_default: default.map(|s| s.into()),
            extra: extra.into(),
            ordinal_position: pos,
        }
    }

    fn col_diff(name: &str, status: DiffStatus, base: Option<ColumnDef>, check: Option<ColumnDef>) -> ObjectDiff<ColumnDef> {
        ObjectDiff { name: name.into(), status, base, check }
    }

    fn changed_table_with_col_diff(col_diffs: Vec<ObjectDiff<ColumnDef>>) -> DatabaseDiff {
        let table = TableDiff {
            name: "users".into(),
            status: DiffStatus::Changed,
            column_diffs: col_diffs,
            index_diffs: vec![],
            fk_diffs: vec![],
            check_diffs: vec![],
        };
        DatabaseDiff {
            name: "mydb".into(),
            status: DiffStatus::Changed,
            tables: vec![table],
            views: vec![], procedures: vec![], functions: vec![], triggers: vec![],
        }
    }

    fn idx(name: &str, unique: bool, idx_type: &str, cols: Vec<(&str, Option<i64>)>) -> IndexDef {
        IndexDef {
            name: name.into(),
            index_type: idx_type.into(),
            is_unique: unique,
            columns: cols.into_iter().enumerate().map(|(i, (col, sp))| IndexColumn {
                column_name: col.into(),
                seq_in_index: (i + 1) as u32,
                sub_part: sp,
            }).collect(),
        }
    }

    fn idx_diff(name: &str, status: DiffStatus, base: Option<IndexDef>, check: Option<IndexDef>) -> ObjectDiff<IndexDef> {
        ObjectDiff { name: name.into(), status, base, check }
    }

    fn changed_table_with_idx_diff(idx_diffs: Vec<ObjectDiff<IndexDef>>) -> DatabaseDiff {
        let table = TableDiff {
            name: "users".into(), status: DiffStatus::Changed,
            column_diffs: vec![], index_diffs: idx_diffs, fk_diffs: vec![], check_diffs: vec![],
        };
        DatabaseDiff {
            name: "mydb".into(), status: DiffStatus::Changed,
            tables: vec![table], views: vec![], procedures: vec![], functions: vec![], triggers: vec![],
        }
    }

    #[test]
    fn test_empty_report_produces_header_only() {
        let (sql, warnings) = generate(&empty_report());
        assert!(sql.contains("Generated by mysql-schema-diff"));
        assert!(sql.contains("base"));
        assert!(sql.contains("check"));
        assert!(warnings.is_empty());
    }

    #[test]
    fn test_same_database_is_skipped() {
        let mut report = empty_report();
        report.databases.push(db_diff("mydb", DiffStatus::Same));
        let (sql, _) = generate(&report);
        assert!(!sql.contains("USE `mydb`"));
    }

    #[test]
    fn test_add_column_only_in_base() {
        let c = col("email", "varchar(255)", false, None, "", 2);
        let db = changed_table_with_col_diff(vec![col_diff("email", DiffStatus::OnlyInBase, Some(c), None)]);
        let mut report = empty_report();
        report.databases.push(db);
        let (sql, warnings) = generate(&report);
        assert!(sql.contains("ALTER TABLE `users` ADD COLUMN `email` varchar(255) NOT NULL"), "got: {}", sql);
        assert!(warnings.is_empty());
    }

    #[test]
    fn test_modify_column() {
        let base_col = col("age", "tinyint", false, None, "", 3);
        let check_col = col("age", "int", false, None, "", 3);
        let db = changed_table_with_col_diff(vec![col_diff("age", DiffStatus::Changed, Some(base_col), Some(check_col))]);
        let mut report = empty_report();
        report.databases.push(db);
        let (sql, warnings) = generate(&report);
        assert!(sql.contains("ALTER TABLE `users` MODIFY COLUMN `age` tinyint NOT NULL"), "got: {}", sql);
        assert!(warnings.is_empty());
    }

    #[test]
    fn test_warn_column_only_in_check() {
        let c = col("old_col", "text", true, None, "", 5);
        let db = changed_table_with_col_diff(vec![col_diff("old_col", DiffStatus::OnlyInCheck, None, Some(c))]);
        let mut report = empty_report();
        report.databases.push(db);
        let (sql, warnings) = generate(&report);
        assert!(sql.contains("-- [WARN]"), "got: {}", sql);
        assert!(sql.contains("-- ALTER TABLE `users` DROP COLUMN `old_col`;"), "got: {}", sql);
        assert_eq!(warnings.len(), 1);
        assert!(warnings[0].contains("old_col"));
    }

    #[test]
    fn test_add_column_with_default_and_extra() {
        let c = col("created_at", "timestamp", false, Some("CURRENT_TIMESTAMP"), "on update CURRENT_TIMESTAMP", 4);
        let db = changed_table_with_col_diff(vec![col_diff("created_at", DiffStatus::OnlyInBase, Some(c), None)]);
        let mut report = empty_report();
        report.databases.push(db);
        let (sql, _) = generate(&report);
        assert!(sql.contains("DEFAULT CURRENT_TIMESTAMP"), "got: {}", sql);
        assert!(sql.contains("on update CURRENT_TIMESTAMP"), "got: {}", sql);
    }

    #[test]
    fn test_add_regular_index() {
        let i = idx("idx_email", false, "BTREE", vec![("email", None)]);
        let db = changed_table_with_idx_diff(vec![idx_diff("idx_email", DiffStatus::OnlyInBase, Some(i), None)]);
        let report = DiffReport { base_label: "b".into(), check_label: "c".into(), generated_at: "t".into(), databases: vec![db] };
        let (sql, _) = generate(&report);
        assert!(sql.contains("ALTER TABLE `users` ADD INDEX `idx_email` (`email`)"), "got: {}", sql);
    }

    #[test]
    fn test_add_unique_index() {
        let i = idx("uq_email", true, "BTREE", vec![("email", None)]);
        let db = changed_table_with_idx_diff(vec![idx_diff("uq_email", DiffStatus::OnlyInBase, Some(i), None)]);
        let report = DiffReport { base_label: "b".into(), check_label: "c".into(), generated_at: "t".into(), databases: vec![db] };
        let (sql, _) = generate(&report);
        assert!(sql.contains("ADD UNIQUE INDEX `uq_email`"), "got: {}", sql);
    }

    #[test]
    fn test_add_primary_key() {
        let i = idx("PRIMARY", false, "BTREE", vec![("id", None)]);
        let db = changed_table_with_idx_diff(vec![idx_diff("PRIMARY", DiffStatus::OnlyInBase, Some(i), None)]);
        let report = DiffReport { base_label: "b".into(), check_label: "c".into(), generated_at: "t".into(), databases: vec![db] };
        let (sql, _) = generate(&report);
        assert!(sql.contains("ADD PRIMARY KEY (`id`)"), "got: {}", sql);
    }

    #[test]
    fn test_partial_index_uses_sub_part() {
        let i = idx("idx_bio", false, "BTREE", vec![("bio", Some(100))]);
        let db = changed_table_with_idx_diff(vec![idx_diff("idx_bio", DiffStatus::OnlyInBase, Some(i), None)]);
        let report = DiffReport { base_label: "b".into(), check_label: "c".into(), generated_at: "t".into(), databases: vec![db] };
        let (sql, _) = generate(&report);
        assert!(sql.contains("`bio`(100)"), "got: {}", sql);
    }

    #[test]
    fn test_hash_index_emits_using_clause() {
        let i = idx("idx_hash", false, "HASH", vec![("token", None)]);
        let db = changed_table_with_idx_diff(vec![idx_diff("idx_hash", DiffStatus::OnlyInBase, Some(i), None)]);
        let report = DiffReport { base_label: "b".into(), check_label: "c".into(), generated_at: "t".into(), databases: vec![db] };
        let (sql, _) = generate(&report);
        assert!(sql.contains("USING HASH"), "got: {}", sql);
    }

    #[test]
    fn test_warn_index_only_in_check() {
        let i = idx("old_idx", false, "BTREE", vec![("x", None)]);
        let db = changed_table_with_idx_diff(vec![idx_diff("old_idx", DiffStatus::OnlyInCheck, None, Some(i))]);
        let report = DiffReport { base_label: "b".into(), check_label: "c".into(), generated_at: "t".into(), databases: vec![db] };
        let (sql, warnings) = generate(&report);
        assert!(sql.contains("-- ALTER TABLE `users` DROP INDEX `old_idx`;"), "got: {}", sql);
        assert_eq!(warnings.len(), 1);
    }

    #[test]
    fn test_changed_index_drops_then_adds() {
        let base_i = idx("idx_x", false, "BTREE", vec![("x", None)]);
        let check_i = idx("idx_x", false, "BTREE", vec![("y", None)]);
        let db = changed_table_with_idx_diff(vec![idx_diff("idx_x", DiffStatus::Changed, Some(base_i), Some(check_i))]);
        let report = DiffReport { base_label: "b".into(), check_label: "c".into(), generated_at: "t".into(), databases: vec![db] };
        let (sql, _) = generate(&report);
        assert!(sql.contains("DROP INDEX"), "got: {}", sql);
        assert!(sql.contains("ADD INDEX"), "got: {}", sql);
    }

    fn fk(name: &str, cols: Vec<&str>, ref_table: &str, ref_cols: Vec<&str>, on_delete: &str, on_update: &str) -> ForeignKeyDef {
        ForeignKeyDef {
            name: name.into(),
            columns: cols.into_iter().map(|s| s.into()).collect(),
            ref_table: ref_table.into(),
            ref_columns: ref_cols.into_iter().map(|s| s.into()).collect(),
            on_delete: on_delete.into(),
            on_update: on_update.into(),
        }
    }

    fn fk_diff(name: &str, status: DiffStatus, base: Option<ForeignKeyDef>, check: Option<ForeignKeyDef>) -> ObjectDiff<ForeignKeyDef> {
        ObjectDiff { name: name.into(), status, base, check }
    }

    fn changed_table_with_fk_diff(fk_diffs: Vec<ObjectDiff<ForeignKeyDef>>) -> DatabaseDiff {
        let table = TableDiff {
            name: "orders".into(), status: DiffStatus::Changed,
            column_diffs: vec![], index_diffs: vec![], fk_diffs, check_diffs: vec![],
        };
        DatabaseDiff {
            name: "mydb".into(), status: DiffStatus::Changed,
            tables: vec![table], views: vec![], procedures: vec![], functions: vec![], triggers: vec![],
        }
    }

    #[test]
    fn test_add_foreign_key() {
        let f = fk("fk_user", vec!["user_id"], "users", vec!["id"], "CASCADE", "RESTRICT");
        let db = changed_table_with_fk_diff(vec![fk_diff("fk_user", DiffStatus::OnlyInBase, Some(f), None)]);
        let report = DiffReport { base_label: "b".into(), check_label: "c".into(), generated_at: "t".into(), databases: vec![db] };
        let (sql, warnings) = generate(&report);
        assert!(sql.contains("ADD CONSTRAINT `fk_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT"), "got: {}", sql);
        assert!(warnings.is_empty());
    }

    #[test]
    fn test_warn_fk_only_in_check() {
        let f = fk("fk_old", vec!["x_id"], "x", vec!["id"], "NO ACTION", "NO ACTION");
        let db = changed_table_with_fk_diff(vec![fk_diff("fk_old", DiffStatus::OnlyInCheck, None, Some(f))]);
        let report = DiffReport { base_label: "b".into(), check_label: "c".into(), generated_at: "t".into(), databases: vec![db] };
        let (sql, warnings) = generate(&report);
        assert!(sql.contains("-- ALTER TABLE `orders` DROP FOREIGN KEY `fk_old`;"), "got: {}", sql);
        assert_eq!(warnings.len(), 1);
    }
}
