use crate::differ::{DatabaseDiff, DiffReport, DiffStatus, ObjectDiff, TableDiff};
use crate::schema::{
    CheckDef, ColumnDef, ForeignKeyDef, IndexDef, RoutineDef, TriggerDef, ViewDef,
};

/// Generate a SQL sync file from a diff report.
///
/// Returns `(sql_content, warnings)`.
/// Warnings should be printed to stderr by the caller.
pub fn generate(report: &DiffReport) -> (String, Vec<String>) {
    let mut out = String::new();
    let mut warnings: Vec<String> = Vec::new();

    out.push_str("-- Generated by mysql-schema-diff\n");
    out.push_str(&format!("-- Base:  {}\n", report.base_label));
    out.push_str(&format!("-- Check: {}\n", report.check_label));
    out.push_str(&format!("-- Date:  {}\n", report.generated_at));
    out.push_str("--\n");
    out.push_str("-- Apply this file to the CHECK instance to sync it with BASE.\n");
    out.push_str("-- Lines with -- [WARN] are commented out: object exists in check but not base.\n");
    out.push_str("-- DELIMITER directives are for mysql CLI; strip them for programmatic APIs.\n");
    out.push('\n');
    out.push_str("SET FOREIGN_KEY_CHECKS = 0;\n");

    for db in &report.databases {
        if db.status == DiffStatus::Same {
            continue;
        }
        let (db_sql, db_warns) = generate_database(db);
        out.push_str(&db_sql);
        warnings.extend(db_warns);
    }

    out.push_str("\nSET FOREIGN_KEY_CHECKS = 1;\n");

    (out, warnings)
}

fn generate_database(db: &DatabaseDiff) -> (String, Vec<String>) {
    let mut out = String::new();
    let mut warnings: Vec<String> = Vec::new();

    out.push_str(&format!(
        "\n-- ============================================================\n\
         -- Database: {}\n\
         -- ============================================================\n",
        db.name
    ));

    match db.status {
        DiffStatus::OnlyInCheck => {
            let msg = format!("database `{}` exists in check but not in base", db.name);
            warnings.push(format!("[WARN] {} — review commented DROP in sync SQL", msg));
            out.push_str(&format!("-- [WARN] {}\n", msg));
            out.push_str(&format!("-- DROP DATABASE IF EXISTS `{}`;\n", db.name));
        }
        DiffStatus::OnlyInBase => {
            out.push_str(&format!("CREATE DATABASE IF NOT EXISTS `{}`;\n", db.name));
            out.push_str(&format!("USE `{}`;\n", db.name));
        }
        DiffStatus::Changed => {
            out.push_str(&format!("USE `{}`;\n", db.name));
        }
        DiffStatus::Same => {}
    }

    (out, warnings)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::differ::*;

    fn empty_report() -> DiffReport {
        DiffReport {
            base_label: "base".into(),
            check_label: "check".into(),
            generated_at: "2026-01-01".into(),
            databases: vec![],
        }
    }

    fn db_diff(name: &str, status: DiffStatus) -> DatabaseDiff {
        DatabaseDiff {
            name: name.into(),
            status,
            tables: vec![],
            views: vec![],
            procedures: vec![],
            functions: vec![],
            triggers: vec![],
        }
    }

    #[test]
    fn test_empty_report_produces_header_only() {
        let (sql, warnings) = generate(&empty_report());
        assert!(sql.contains("Generated by mysql-schema-diff"));
        assert!(sql.contains("base"));
        assert!(sql.contains("check"));
        assert!(warnings.is_empty());
    }

    #[test]
    fn test_same_database_is_skipped() {
        let mut report = empty_report();
        report.databases.push(db_diff("mydb", DiffStatus::Same));
        let (sql, _) = generate(&report);
        assert!(!sql.contains("USE `mydb`"));
    }
}
